linters:
  enable-all: true
  disable:
    - asciicheck
    - depguard
    - dupl
    - errname
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - funlen
    - gci
    - gochecknoglobals
    - gocognit
    - goconst
    - godot
    - godox
    - goerr113
    - gofumpt
    - gomnd
    - lll
    - musttag
    - nestif
    - nilnil
    - nlreturn
    - paralleltest
    - prealloc
    - revive
    - tagalign
    - tagliatelle
    - testpackage
    - unparam
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
    # deprecated linters
    - deadcode
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

linters-settings:
  gosec:
    # all rules enabled
    # see also: https://securego.io/docs/rules/rule-intro.html
    config:
      global:
        # allow #nosec override comments
        nosec: enabled
        # disable potentially noisy stricter audit mode
        audit: disabled
      G101: # "Look for hard-coded credentials"
        mode: strict
  cyclop:
    max-complexity: 20
